<?php

defined('BASEPATH') OR exit('No direct script access allowed');

// This can be removed if you use __autoload() in config.php OR use Modular Extensions
require APPPATH . '/libraries/REST_Controller.php';

/**
 * This is an example of a few basic user interaction methods you could use
 * all done with a hardcoded array
 *
 * @package         CodeIgniter
 * @subpackage      Rest Server
 * @category        Controller
 * @author          Phil Sturgeon, Chris Kacerguis
 * @license         MIT
 * @link            https://github.com/chriskacerguis/codeigniter-restserver
 */
class Example extends REST_Controller {

    function __construct()
    {
        // Construct the parent class
        parent::__construct();

        // Configure limits on our controller methods
        // Ensure you have created the 'limits' table and enabled 'limits' within application/config/rest.php
        $this->methods['user_get']['limit'] = 500; // 500 requests per hour per user/key
        $this->methods['user_post']['limit'] = 100; // 100 requests per hour per user/key
        $this->methods['user_delete']['limit'] = 50; // 50 requests per hour per user/key
    }

    public function patients_get()
    {
        // Users from a data store e.g. database
        $users = [
            ['id' => 1, 'first' => 'John', 'last' => 'Patient', 'phone' => '555-555-5555', 'ssn' => '000-00-0000', 'dob' => '1987-02-13', 'gender' => 'male'],
            //['id' => 2, 'name' => 'Jim', 'email' => 'jim@example.com', 'fact' => 'Developed on CodeIgniter'],
            ['id' => 2, 'first' => 'Emma', 'last' => 'Patient', 'phone' => '555-555-5555', 'ssn' => '000-00-0000', 'dob' => '1971-06-23', 'gender' => 'female'],
            ['id' => 3, 'first' => 'Arthur', 'last' => 'Patient', 'phone' => '555-555-5555', 'ssn' => '000-00-0000', 'dob' => '1927-02-13', 'gender' => 'male'],
            //['id' => 3, 'name' => 'Jane', 'email' => 'jane@example.com', 'fact' => 'Lives in the USA', ['hobbies' => ['guitar', 'cycling']]],
        ];

        $id = $this->get('id');

        // If the id parameter doesn't exist return all the users

        if ($id === NULL)
        {
            // Check if the users data store contains users (in case the database result returns NULL)
            if ($users)
            {
                // Set the response and exit
                $this->response($users, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
            }
            else
            {
                // Set the response and exit
                $this->response([
                    'status' => FALSE,
                    'message' => 'No users were found'
                ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
            }
        }

        // Find and return a single record for a particular user.

        $id = (int) $id;

        // Validate the id.
        if ($id <= 0)
        {
            // Invalid id, set the response and exit.
            $this->response(NULL, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code
        }

        // Get the user from the array, using the id as key for retreival.
        // Usually a model is to be used for this.

        $user = NULL;

        if (!empty($users))
        {
            foreach ($users as $key => $value)
            {
                if (isset($value['id']) && $value['id'] === $id)
                {
                    $user = $value;
                }
            }
        }

        if (!empty($user))
        {
            $this->set_response($user, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
        }
        else
        {
            $this->set_response([
                'status' => FALSE,
                'message' => 'User could not be found'
            ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
        }
    }

    public function users_post()
    {
        // $this->some_model->update_user( ... );
        $message = [
            'id' => 100, // Automatically generated by the model
            'name' => $this->post('name'),
            'email' => $this->post('email'),
            'message' => 'Added a resource'
        ];

        $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
    }

    public function users_delete()
    {
        $id = (int) $this->get('id');

        // Validate the id.
        if ($id <= 0)
        {
            // Set the response and exit
            $this->response(NULL, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code
        }

        // $this->some_model->delete_something($id);
        $message = [
            'id' => $id,
            'message' => 'Deleted the resource'
        ];

        $this->set_response($message, REST_Controller::HTTP_NO_CONTENT); // NO_CONTENT (204) being the HTTP response code
    }

    ///////

    public function instances_get()
    {
        // Users from a data store e.g. database
        $users = [
            ['id' => 1, 'Enc #' => '161000', 'Status' => 'Open', 'Location' => '1', 'Doctor' => '2234', 'Acct #' => 'xxxxx-xx-xxx', 'Chart #' => 'xxxx', 'Last Name'=>'Patient', 'First Name'=>'John', 'Date'=>'04/10/14', 'Time'=>'11:05a', 'Type'=>'71020', 'Code'=>'12345', 'Dx 1'=>'793.19', 'Dx 2'=>'793.19', 'Dx 3'=>'793.19', 'Dx Printed'=>'00/00/00'],
            ['id' => 2, 'Enc #' => '161001', 'Status' => 'Closed', 'Location' => '9', 'Doctor' => '4321', 'Acct #' => 'xxxxx-xx-xxx', 'Chart #' => 'xxxx', 'Last Name'=>'Patient', 'First Name'=>'Emma', 'Date'=>'10/13/13', 'Time'=>'01:35p', 'Type'=>'02019', 'Code'=>'12345', 'Dx 1'=>'793.19', 'Dx 2'=>'793.19', 'Dx 3'=>'793.19', 'Dx Printed'=>'00/00/00'],
            ['id' => 3, 'Enc #' => '161002', 'Status' => 'Open', 'Location' => '12', 'Doctor' => '0192', 'Acct #' => 'xxxxx-xx-xxx', 'Chart #' => 'xxxx', 'Last Name'=>'Patient', 'First Name'=>'Arthur', 'Date'=>'07/21/15', 'Time'=>'03:40p', 'Type'=>'09675', 'Code'=>'12345', 'Dx 1'=>'793.19', 'Dx 2'=>'793.19', 'Dx 3'=>'793.19', 'Dx Printed'=>'00/00/00']
        ];

        $id = $this->get('id');

        // If the id parameter doesn't exist return all the users

        if ($id === NULL)
        {
            // Check if the users data store contains users (in case the database result returns NULL)
            if ($users)
            {
                // Set the response and exit
                $this->response($users, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
            }
            else
            {
                // Set the response and exit
                $this->response([
                    'status' => FALSE,
                    'message' => 'No users were found'
                ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
            }
        }

        // Find and return a single record for a particular user.

        $id = (int) $id;

        // Validate the id.
        if ($id <= 0)
        {
            // Invalid id, set the response and exit.
            $this->response(NULL, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code
        }

        // Get the user from the array, using the id as key for retreival.
        // Usually a model is to be used for this.

        $user = NULL;

        if (!empty($users))
        {
            foreach ($users as $key => $value)
            {
                if (isset($value['id']) && $value['id'] === $id)
                {
                    $user = $value;
                }
            }
        }

        if (!empty($user))
        {
            $this->set_response($user, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
        }
        else
        {
            $this->set_response([
                'status' => FALSE,
                'message' => 'User could not be found'
            ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
        }
    }

    public function providers_get()
    {
        // Users from a data store e.g. database
        $users = [
           ['id' => 97211, 'DRD_Definition' => '039 - EXTRACRANIAL PROCEDURES W/O CC/MCC', 'Provider_Id' => '330005', 'Provider_Name' => 'KALEIDA HEALTH', 'Provider Street Address' => '726 EXCHANGE STREET SUITE 522', 'Provider_City' => 'BUFFALO', 'Provider_State' => 'NY', 'Provider Zip Code'=>'14210', 'Hospital Referral Region Description'=>'NY - Buffalo', 'Total_Discharges'=>'23','Average_Covered_Charges'=>'27984.4', 'Average_Total_Payments'=>'7567.39', 'DRD'=>'039'],
           ['id' => 97211, 'DRD_Definition' => '039 - EXTRACRANIAL PROCEDURES W/O CC/MCC', 'Provider_Id' => '330005', 'Provider_Name' => 'KALEIDA HEALTH', 'Provider Street Address' => '726 EXCHANGE STREET SUITE 522', 'Provider_City' => 'BUFFALO', 'Provider_State' => 'NY', 'Provider Zip Code'=>'14210', 'Hospital Referral Region Description'=>'NY - Buffalo', 'Total_Discharges'=>'23','Average_Covered_Charges'=>'27984.4', 'Average_Total_Payments'=>'7567.39', 'DRD'=>'039'],
           ['id' => 97211, 'DRD_Definition' => '039 - EXTRACRANIAL PROCEDURES W/O CC/MCC', 'Provider_Id' => '330005', 'Provider_Name' => 'KALEIDA HEALTH', 'Provider Street Address' => '726 EXCHANGE STREET SUITE 522', 'Provider_City' => 'BUFFALO', 'Provider_State' => 'NY', 'Provider Zip Code'=>'14210', 'Hospital Referral Region Description'=>'NY - Buffalo', 'Total_Discharges'=>'23','Average_Covered_Charges'=>'27984.4', 'Average_Total_Payments'=>'7567.39', 'DRD'=>'039']
        ];

        $id = $this->get('id');

        // If the id parameter doesn't exist return all the users

        if ($id === NULL)
        {
            // Check if the users data store contains users (in case the database result returns NULL)
            if ($users)
            {
                // Set the response and exit
                $this->response($users, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
            }
            else
            {
                // Set the response and exit
                $this->response([
                    'status' => FALSE,
                    'message' => 'No users were found'
                ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
            }
        }

        // Find and return a single record for a particular user.

        $id = (int) $id;

        // Validate the id.
        if ($id <= 0)
        {
            // Invalid id, set the response and exit.
            $this->response(NULL, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code
        }

        // Get the user from the array, using the id as key for retreival.
        // Usually a model is to be used for this.

        $user = NULL;

        if (!empty($users))
        {
            foreach ($users as $key => $value)
            {
                if (isset($value['id']) && $value['id'] === $id)
                {
                    $user = $value;
                }
            }
        }

        if (!empty($user))
        {
            $this->set_response($user, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
        }
        else
        {
            $this->set_response([
                'status' => FALSE,
                'message' => 'User could not be found'
            ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
        }
    }

    public function diagnoses_get()
    {
        // Users from a data store e.g. database
        $users = [
           ['id' => 97211, 'patient_id'=>'1', 'DRD_Definition' => '039 - EXTRACRANIAL PROCEDURES W/O CC/MCC', 'Provider_Id' => '330005', 'Provider_Name' => 'KALEIDA HEALTH', 'Gender' => '0', 'Smoke' => '0', 'TNM' => '', 'Zip Code'=>'14210', 'Cancer History'=>'Cervical', 'Medical History'=>'Allergies', 'DRD'=>'039', 'Classification'=>'0'],
           ['id' => 87156, 'patient_id'=>'2', 'DRD_Definition' => '039 - EXTRACRANIAL PROCEDURES W/O CC/MCC', 'Provider_Id' => '330005', 'Provider_Name' => 'KALEIDA HEALTH', 'Gender' => '1', 'Smoke' => '0', 'TNM' => 'T1 N2 M1', 'Zip Code'=>'14210', 'Cancer History'=>'Lung', 'Medical History'=>'Ulcers', 'DRD'=>'039', 'Classification'=>'1'],
           ['id' => 90287, 'patient_id'=>'3', 'DRD_Definition' => '039 - EXTRACRANIAL PROCEDURES W/O CC/MCC', 'Provider_Id' => '330005', 'Provider_Name' => 'KALEIDA HEALTH', 'Gender' => '0', 'Smoke' => '1', 'TNM' => '', 'Zip Code'=>'14210', 'Cancer History'=>'Colon', 'Medical History'=>'Heart Murmur', 'DRD'=>'039', 'Classification'=>'0']
        ];

        $id = $this->get('id');

        // If the id parameter doesn't exist return all the users

        if ($id === NULL)
        {
            // Check if the users data store contains users (in case the database result returns NULL)
            if ($users)
            {
                // Set the response and exit
                $this->response($users, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
            }
            else
            {
                // Set the response and exit
                $this->response([
                    'status' => FALSE,
                    'message' => 'No users were found'
                ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
            }
        }

        // Find and return a single record for a particular user.

        $id = (int) $id;

        // Validate the id.
        if ($id <= 0)
        {
            // Invalid id, set the response and exit.
            $this->response(NULL, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code
        }

        // Get the user from the array, using the id as key for retreival.
        // Usually a model is to be used for this.

        $user = NULL;

        if (!empty($users))
        {
            foreach ($users as $key => $value)
            {
                if (isset($value['id']) && $value['id'] === $id)
                {
                    $user = $value;
                }
            }
        }

        if (!empty($user))
        {
            $this->set_response($user, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
        }
        else
        {
            $this->set_response([
                'status' => FALSE,
                'message' => 'User could not be found'
            ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
        }
    }

}